### ISSUE TITLE
Caught exception not handled properly

### ISSUE THREAD

**Issue by jwhitex** [opbeat/opbeat-react#12]
The below code does not properly handle the case when `msg` is an `ErrorEvent`. 

*Console Error:*
Uncaught TypeError: exception.message.indexOf is not a function.

*Thrown here:*
```
  var exception = {
    'message': error ? error.message : msg,
    'type': error ? error.name : null,
    'fileurl': file || null,
    'lineno': line || null,
    'colno': col || null,
    'extra': extraContext
  }

  if (!exception.type) {
    // Try to extract type from message formatted like 'ReferenceError: Can't find variable: initHighlighting'
    if (exception.message.indexOf(':') > -1) {
      exception.type = exception.message.split(':')[0]
    }
  }
```

*Code Generating the error in react component:*
```
 throwError = () => {
    throw new Error();
  }
```

**Comment by jahtalab** [comment]
@jwhitex,
Thanks for reporting the issue.
We're working on this bug and will release a fix soon.

**Comment by jahtalab** [comment]
@jwhitex , version 3.3.0 includes the fix for this. 
Let me know how it goes.

**Comment by jwhitex** [comment]
@jahtalab Looks good! Thanks 👍
