### ISSUE TITLE
Error reporting “breaks” when ran through Cordova

### ISSUE THREAD

**Issue by thomaslindstrom** [opbeat/opbeat-react#17]
```
{
    "error_message": "Unable to validate data.", 
    "structured_error": {
        "http": {
            "url": "must be the full URL, including scheme and host: got file:///var/containers/Bundle/Application/495CFDD5-3A8C-4D64-AF85-DFBBDA4B4FF4/my.app/www/index.html/#/settings"
        }
    }, 
    "status": 400
}
```

File URLs should be supported, IMO.
*Worst case:* Is it possible to override the URL before sending it to the Opbeat API?

**Comment by jahtalab** [comment]
@thomaslindstrom ,

Thanks for reporting the issue and sorry about the slow response.

Unfortunately we don't support Cordova yet and it's not possible to change the URL before sending it to the server.
I will make sure to update this issue when there are any updates.

Cheers
