### ISSUE TITLE
Not working in production

### ISSUE THREAD

**Issue by djbobbydrake** [opbeat/opbeat-react#21]
Followed the instructions and things are working for me locally. On the production site, however, they're not. Are there any babelrc or webpack settings that may cause opbeat not to work in production?

**Comment by hmdhk** [comment]
@djbobbydrake ,

Thanks for reaching out.
Just to be clear, the problem is that opbeat-react doesn't send any data to the server?
Also, do you see any errors in your console or any failing Http request in the network tab?

**Comment by djbobbydrake** [comment]
@jahtalab No network requests are being sent to opbeat. No errors in console either. Would it make a difference if our js bundles are hosted on cloudfront in production? Although I'd still expect an OPTIONS request if it were a CORS issue. I do see the opbeat js in our minified bundle.

**Comment by hmdhk** [comment]
@djbobbydrake, Would you please send your configuration to our support email support@opbeat.com with a short description of the issue. I will take it from there.

**Comment by djbobbydrake** [comment]
@jahtalab will do. Thanks!
