### ISSUE TITLE
30 kB gzipped overhead

### ISSUE THREAD

**Issue by oliviertassinari** [opbeat/opbeat-react#22]
Using opbeat-react client side introduce a 30 kB gzipped overhead in our bundle.
I fear it's a blocker for us, especially for a performance analytic tool. It's about the size of react-dom, which is already large.
Do you have any plan for reducing the size of the library?

**Comment by hmdhk** [comment]
Thanks for reaching out @oliviertassinari ,

Unfortunately for the full functionality the package size can't be reduced. However we're looking into more efficient ways to bundle our module as well as providing multiple packages for different use-cases.
