### ISSUE TITLE
3.2.0 swallows errors.. exceptions aren't visible in console

### ISSUE THREAD

**Issue by jgentes** [opbeat/opbeat-react#9]
To reproduce, a add `throw new Error('test')` in a jsx file and it won't appear in the console

Culprit code appears to be here:
```
ReactInstrumentation.debugTool.onBeginLifeCycleTimer(debugID, timerType);
  try {
    return fn();
  } finally {
    ReactInstrumentation.debugTool.onEndLifeCycleTimer(debugID, timerType);
  }
```

**Comment by broofa** [comment]
[Source link](https://github.com/facebook/react/blob/b840229286ac2a82fa49553ce793cf7b953d1845/src/renderers/shared/stack/reconciler/ReactCompositeComponent.js#L60-L66)

**Comment by jgentes** [comment]
This appeared to be a problem caused by loading another logging solution (logrocket) after opbeat-react in the webpack config. Here's the working snippet of the webpack entry property:
```
vendor: [ 
      'babel-polyfill',
      'logrocket',
      'logrocket-react',
      'opbeat-react',
      'axios',
```
